dist: xenial
sudo: required
language: java
jobs:
  fast_finish: true
  include:
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: openjdk11
  
  - os: linux
    arch: aarch64
    jdk: openjdk8
    script: "mvn install -DskipTests"
    addons:
      apt:
        packages:
          - maven
          - openjdk-8-jdk  
  - os: linux
    dist: bionic
    arch: aarch64
    jdk: openjdk11
    script: "mvn install -DskipTests"
    addons:
      apt:
        packages:
          - maven
          - openjdk-11-jdk
  - build: s390x # custom job identifier to be referenced in the allow_failures section
    os: linux
    arch: s390x
    jdk: openjdk11
    script: "mvn install -DskipTests"
    addons:
      apt:
        packages:
          - maven
  allow_failures:
  - build: s390x
services:
- docker
before_install:
- gem install asciidoctor
script:
  - "./.travis/build.sh"
env:
  global:
    - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
    - BRANCH=${TRAVIS_BRANCH:-master}
    - TAG=${TRAVIS_TAG:-latest}
    - MVN_ARGS="-B"
    - TESTCONTAINERS_RYUK_DISABLED=TRUE
    - secure: x+/dNLqAA7GVihb8Cx0/VXyTbAIslFcAPSeq6tDOXrpQqbDzC/LZ8Qzs/OpC6m3Htjogkk85Sibe8RRcxq4ENPUpjx7YZ2pxh2Wye5fjhqX2HVTVE8AQBlKLH/3BaayibzCmc4ydM6daf4gUNq0WTNq5FmW0vUf4dfeICMzbKHMYWVBwDisCiTqCmAXldIm4qoxBoxuSO02Tsfc6cZxXLmjhNGzlwkGOJHnURSGYk5GGM8SFTU4gCJAbSFZSVDGaFvvX9+YRL0UYS505QzPvQqlBizv4szhjx9E67u3px3D5kCOOlteX/npWPQQjr2n2Mi6P0cyC8lwF0Qbcqx/CK+XWlfz+i1wgN6okNVtArsDmFgB/HDLyi9SZkT3WCks6TyObxEJELptbv08YBMydH37SyX8PMeY3tkyUcgByiiQX7M4CZL57sNJ8vJyu21Wv65oZdRETeLlbh1PksqAuP08ldZy73l4NgN8czLlyFY1ujhjk5VZPfQEY5ec5O7I1IRGL6NBpeEc7C//GZRrsBvt39Axwotr7ZOoDcaFBJhs8J5ggsu/zSpf54fiAUy+xMLqc8wD2ujc+3IvD2PUzqxZHT590FrZq/VMrzxm+J0AX729rN69vGcnUCLq6rJclx+ET7Bj4qtuLDIufJPAgAdQwE/BAv1nWE0EIh7JT2GE= #DOCKER_USER
    - secure: Oz8ba2oujxWvnHs7QZjYbGw997Af19U5IVy6+dgoN/dQ+XIwKL+65V4VlbInulCIOC0fOx5sRzU0cnSUccrYo7vZylgw8b1JUfYVoXwktvZteyLjEt7FJN9zSm8IEdshSEqfgl9MoYzPUQxHwcYvykL9rfxwgpVXqSPxu8gR36Ilb5bvA6nhYzzzzJRldGy63vNTKJx6Up7dxLwLClAPOZ8Uk2yYO7WbZsDDT4+0XsejRbcpz7CzvFGlC2pX3fdv9/k5Sev8SSKjOkWBgBgeYz78XuEng+JZ1F5SfVwoKbAdz3s4XSVVpgNfWKjsMIehWvpZlXVmE7KHjJ51QdduQlHeRjjnAKCwZGW/e0d8btGaaYduZnbIfHt/kVZmje0m1AhATY07tCPXrTB7Lc5oqrZ1+ULG777nHFilTXGukQoX1Ck264jZm0uXByeJ/aascQrRqDiYGNjiWJnToCJouVxsqwnAmJ4DOmt8eAwCW9m0uQB+D6huyGKTXiZR7G6O5CPF8AtGs2JZOk52/Oty4d6/x3wiQHUQ4TGtbKuCqLz4YF+rMffbyj8vDtJqGVGibENSlFY47VayiURgMwTx19p9A8FaajBwNe85Bq6JIjQgMdE/vj+zdlh342vnq/LpMcyc/twshnuR6mjBQokm0RfCF5RNQBHVPfb0FJ6MTYs= #DOCKER_PASS
